spring:
  application:
    name: fruitsfinder-product

# Datasource configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      #dialect: org.hibernate.dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${DATABASE_NAME:products}
    #url: jdbc:h2:mem:memDb;DB_CLOSE_DELAY=-1
    username: root
    #username: sa
    password: my-secret-pw
    #password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: org.h2.Driver
  #h2:
    #console:
      #enabled: true
      #path: /h2
logging:
  level:
    org:
      zalando:
        logbook: TRACE
logbook:
  include:
    - /api/**
    - /actuator/**
  exclude:
    - /actuator/health
    - /api/admin/**
  filter.enabled: true
  secure-filter.enabled: true
  format.style: http
  strategy: body-only-if-status-at-least
  minimum-status: 400
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  write:
    chunk-size: 1000