spring:
  application:
    name: sakanfinder-product

# Datasource configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      dialect: org.hibernate.dialect
  datasource:
    #url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${DATABASE_NAME:products}
    url: jdbc:h2:mem:memDb;DB_CLOSE_DELAY=-1
    #username: root
    username: sa
    #password: my-secret-pw
    password:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2